version: '3.9'

services:
  web:
    build: .
    command: sh -c "./entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    # depends_on:
    #   - db

#   db:
#     image: postgres
#     restart: always
#     ports:
#       - 5432:5432
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword

# volumes:
#   postgres_data:
